server:
  port: 8888

spring:
  application:
    name: superchat_api
  profiles:
    active: local-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/superchat_db
    username: superchat
    password: sup3rch4t*
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

superchat:
  app:
    user-password: qwerty10*
    jwtSecret: s3cr3tk3y*
    jwtExpirationMs: 86400000
  external:
    crypto-api:
      keyHeader: X-CoinAPI-Key
      key: 3AB2C94E-DB20-4A9D-B94B-6CE52EF55C86
      url: https://rest-sandbox.coinapi.io/
      pathAsset: /v1/assets?filter_asset_id=
  queue-user:
    name: queue-user
    exchange: exchange-user
    routingKey: routing-key-user
  queue-message:
    name: queue-message
    exchange: exchange-message
    routingKey: routing-key-message