server:
  port: 8888

spring:
  application:
    name: superchat_api
  profiles:
    active: local-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/superchat_db
    username: superchat
    password: sup3rch4t*
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

superchat:
  app:
    user-password: qwerty10*
    jwtSecret: s3cr3tk3y*
    jwtExpirationMs: 86400000
  queue-user:
    name: queue-user
    exchange: exchange-user
    routingKey: routing-key-user